# Generated by Django 5.1.2 on 2024-12-28 10:49
import django.utils.timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_timestamp_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
