# Generated by Django 5.1.2 on 2024-12-28 11:06
import django.utils.timezone
from django.db import migrations

def set_default_time(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        if article.timestamp is None:
            article.timestamp = django.utils.timezone.now
        if article.updated is None:
            article.updated = django.utils.timezone.now
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_timestamp_alter_article_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='created',
        ),
    ]
