# Generated by Django 5.1.2 on 2025-06-07 07:40

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.user_profile_upload_handler),
        ),
    ]
