# Generated by Django 5.1.2 on 2025-01-09 13:29

import django.db.models.deletion
import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredients_recipe_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipes.recipeingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipes.validators.validate_unit]),
        ),
    ]
