# Generated by Django 5.1.2 on 2025-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='float_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
