# Generated by Django 5.1.2 on 2025-01-11 13:55

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeingredients_float_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='float_quantity',
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.CharField(max_length=50, validators=[recipes.validators.validate_qty]),
        ),
    ]
