# Generated by Django 5.1.2 on 2025-01-21 14:10

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.FloatField(max_length=50, validators=[recipes.validators.validate_qty]),
        ),
    ]
