# Generated by Django 5.1.2 on 2025-01-21 14:13

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.CharField(max_length=50, validators=[recipes.validators.validate_qty]),
        ),
    ]
