# Generated by Django 5.1.2 on 2025-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='float_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
