# Generated by Django 5.1.2 on 2025-03-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipeimage_delete_recipeingredientimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='ingredient',
            new_name='recipe',
        ),
    ]
