# Generated by Django 5.1.2 on 2025-03-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_rename_ingredient_recipeimage_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipes.recipe')),
        ),
    ]
