# Generated by Django 5.1.2 on 2025-03-14 13:24

import recipes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipes.utils.recipe_image_upload_handler),
        ),
    ]
